version: '3.7'

services:
  seleniumhub:
    image: selenium/hub:3.0.1
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
      VIRTUAL_HOST: selenium.hub.docker
    ports:
      - "4444:4444"
    networks:
      - nightwatch-docker-grid-network
    restart: always
    logging: &LOG
      options:
        max-file: '5'
        max-size: 1m

  jenkins:
    image: jenkins/jenkins:lts
    container_name: MyJenkins
    restart: always
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  node-chrome:
    image: selenium/node-chrome:3.0.1
    environment: &SELENIUM_NODE_ENV
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: 4444
    restart: always
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  node-chrome-debug:
    image: selenium/node-chrome-debug:3.0.1
    environment:
      <<: *SELENIUM_NODE_ENV
    restart: always
    ports:
      - "5900:5900"
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  node-firefox:
    image: selenium/node-firefox:3.0.1
    environment:
      <<: *SELENIUM_NODE_ENV
    restart: always
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  node-firefox-debug:
    image: selenium/node-firefox-debug:3.0.1
    environment:
      <<: *SELENIUM_NODE_ENV
    restart: always
    ports:
      - "5901:5900"
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

  web:
    image: mycargus/hello_docker_world:latest
    environment:
      VIRTUAL_HOST: hello.docker
    restart: always
    networks:
      - nightwatch-docker-grid-network
    logging: *LOG

networks:
  nightwatch-docker-grid-network:
    driver: bridge
    name: nightwatch-docker-grid-network
